name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Check TypeScript syntax
        run: npm run type-check

      - name: Check syntax with eslint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e:ci
