name: AMFI Bot website CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check syntax/types
        run: pnpm full-check

      - name: Run unit tests
        run: pnpm test:unit

      - name: Build a project
        run: pnpm build
